# Generated by Django 5.1.7 on 2025-08-30 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
